### ISSUE TITLE
【求助】请问应该如何实现按钮级别的权限

### ISSUE THREAD

**Issue by ngxlua** [RealLiuSha/echo-admin#2]
感谢作者设计了 echo-admin ， 总体我认为比 gin 的实现好很多， 代码整体也比较简洁

我想问一下， 如何实现按钮级别的权限控制， 希望能回复， 谢谢

**Comment by RealLiuSha** [comment]
@ngxlua  现在的策略已经细化到资源了， 如果你希望控制某个按钮的权限， 只需要对应配置资源即可， 可以参考在线示例

[admin](https://admin.srelab.cn/#/)

你会发现，你没有任何变更权限

**Comment by ngxlua** [comment]
@RealLiuSha  才看到回复， 不好意思， 我想知道的是如何实现按钮级别的展示权限，谢谢作者

**Comment by RealLiuSha** [comment]
@ngxlua 月底会发个版本支持判断前端按钮的展示权限

**Comment by RealLiuSha** [comment]
@ngxlua  已解决
