### ISSUE TITLE
三级子菜单页面加载BUG

### ISSUE THREAD

**Issue by starchou** [RealLiuSha/echo-admin#3]
新增的三级子菜单，使用的vue组件路由不生效，发现使用的是二级菜单的组件路由

**Comment by starchou** [comment]
![1811622638748_ pic](https://user-images.githubusercontent.com/3644838/120606966-4fe2fa80-c482-11eb-86ef-5fe02bf4d232.jpg)
![3311622706204_ pic](https://user-images.githubusercontent.com/3644838/120607089-7143e680-c482-11eb-9d5d-bbf964b9362a.jpg)

**Comment by RealLiuSha** [comment]
感谢反馈， 已处理。
