### ISSUE TITLE
https://admin.liusha.me/#/login?redirect=%2F

### ISSUE THREAD

**Issue by renektonwu** [RealLiuSha/echo-admin#5]
验证码一直不通过，登陆不进去，是不是后台挂了，大佬

**Comment by RealLiuSha** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/5715152/177545633-40d4ff3c-476a-4b9e-88c3-e11f508bb45f.png">
@renektonwu

**Comment by dineshsiprtc** [comment]
UI is not working. no default user in the system. Please let me  know how to get the English version UI

![26 11 2023_12 00 54_REC](https://github.com/RealLiuSha/echo-admin/assets/150108336/7d28f87d-6df9-4a25-b973-a874e85866d8)

# readonly account
username: test
password: 123123
